// Generated by CoffeeScript 1.6.1
(function() {
  var sections_height;

  $(document).ready(function() {
    return sections_height(577);
  });

  sections_height = function(min) {
    var array, set_height, set_heights;
    array = ['header', 'section.s1', 'section.s2', 'section.s3', 'section.s4', 'section.s5', 'section.s6', 'section.s7', 'section.s9'];
    set_heights = function(array) {
      var elem, px, _i, _len, _results;
      px = $(window).height();
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        elem = array[_i];
        _results.push(set_height(elem, px));
      }
      return _results;
    };
    set_height = function(elem, px) {
      if (px < min) {
        px = min;
      }
      return $(elem).height(px);
    };
    set_heights(array);
    return $(window).resize(function() {
      return set_heights(array);
    });
  };

}).call(this);
